# Лабораторна робота № 3
## Діагностика шкал вимірювання

Курс СК26 «Інтелектуальний аналіз та візуалізація даних»

**Тривалість:** 2 год аудиторно + 3 год самостійно · **Оцінка:** 4 бали
**Файли:** `Ковід_дані_навчальні.xlsx`, `ЛР3_помилковий_аналіз.ipynb`

---

Шкала вимірювання визначає, які операції над змінною взагалі мають сенс.
Комп'ютер цього не знає: він порахує середнє від номера телефону й не поскаржиться.
Знати має вимірювач.

У цій роботі ви складаєте **паспорт восьми змінних** свого варіанта, показуєте на
власних даних, які статистики для них недопустимі, і виправляєте чужий аналіз,
де таких помилок десять.

In [1]:
ПРІЗВИЩЕ_ІМЯ = 'Роман Бойко'      # напишіть тут своє прізвище та ім'я
ГРУПА        = 'ШІ-32'
НОМЕР        = 4       # ваш номер за списком групи (1–30)

assert ПРІЗВИЩЕ_ІМЯ and ГРУПА and НОМЕР, 'Заповніть три поля вище'
assert 1 <= НОМЕР <= 30, 'Номер має бути від 1 до 30'

In [2]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_colwidth', 60)

with open('lr3_variants_student.json', 'r', encoding='utf-8') as f:
    ВАРІАНТИ = json.load(f)
В = ВАРІАНТИ[НОМЕР - 1]

print('=' * 74)
print(f'ВАРІАНТ {В["варіант"]}   ·   {ПРІЗВИЩЕ_ІМЯ}   ·   {ГРУПА}')
print('=' * 74)
print()
print('Ваші вісім стовпців:')
for i, c in enumerate(В['стовпці'], 1):
    print(f'   {i}. {c}')
print()
print('Ваша пара для аналізу зв’язку:', ' та '.join(В['пара']))
print()
print('Ваше додаткове питання:')
print('  ', В['питання'])

==========================================================================
ВАРІАНТ 4   ·   Роман Бойко   ·   ШІ-32
==========================================================================

Ваші вісім стовпців:
   1. Телефон
   2. Ускладнення
   3. Перебіг
   4. Виписка
   5. Ліжко днів
   6. Д-дим1
   7. Фібрин2
   8. МНВ2

Ваша пара для аналізу зв’язку: ступінь КТ та ЛН

Ваше додаткове питання:
   У чому різниця між шкалою інтервалів і шкалою відношень? Знайдіть у файлі по одному прикладу кожної та поясніть, яка операція допустима для другої, але не для першої.

In [3]:
ФАЙЛ = 'Ковід_дані_навчальні.xlsx'
df = pd.read_excel(ФАЙЛ, sheet_name='Лист1', engine='openpyxl')
МОЇ = В['стовпці']

print('Розмір набору:', df.shape)
df[МОЇ].head(8)

Розмір набору: (121, 77)

,Телефон,Ускладнення,Перебіг,Виписка,Ліжко днів,Д-дим1,Фібрин2,МНВ2
0,0958469788 дружина Ганна,"тромбоз підколінної артерії, гангрена? ТЕЛА? СЛН ГРДС",важкий,2022-03-10 00:00:00,14,NaN,2.30,239
1,"0671778486, 0994887663 дружина Оксана",NaN,важкий,2022-03-16 00:00:00,22,3316,3.40,1.08
2,"0958768045, чоловік Степан 0951784726",NaN,важкий,2022-01-18 00:00:00,20,NaN,3.27,1.18
3,0959819331. дочка Валентина 0960845205,NaN,важкий,2022-01-13 00:00:00,20,NaN,4.00,1.07
4,"0952294866, дочка Дарина 0678360161",NaN,важкий,2022-03-11 00:00:00,27,NaN,3.37,2.18
5,0959922983 сестра Софія,"Респірат дестрес синдром, емфізема легень, СЛН",важкий,2021-12-26 00:00:00,9(5 у реан),8000,3.00,2015-01-01 00:00:00
6,"0998073702, дружина Наталія 0998382226",NaN,важкий,2022-05-11 00:00:00,18,183,3.12,1.09
7,"0637258771, син Сергій 0968413301",NaN,серед важ,2022-05-28 00:00:00,10,3028,2.40,1.09

---
# Етап 1. Паспорт змінних

Для кожного з восьми стовпців визначте шкалу вимірювання. Спирайтеся не на тип даних
у pandas, а на **зміст величини**: що означають її значення і які порівняння між ними
мають сенс.

Нагадування:

| Шкала | Ознака |
|---|---|
| Номінальна | значення можна лише порівняти на рівність |
| Порядкова | є природний порядок, але відстані між сусідніми рівнями невідомі |
| Інтервальна | різниці мають сенс, нуль умовний |
| Відношень | є природний нуль, відношення мають сенс |
| Абсолютна | природні і нуль, і одиниця вимірювання |

Окремо позначайте **ідентифікатори** — значення, що не є величиною взагалі
(номер історії хвороби, прізвище, телефон).

In [4]:
# Спершу подивіться, що каже pandas — і не довіряйте йому
df[МОЇ].info()

<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Телефон      120 non-null    object
 1   Ускладнення  61 non-null     str
 2   Перебіг      121 non-null    str
 3   Виписка      120 non-null    object
 4   Ліжко днів   120 non-null    object
 5   Д-дим1       59 non-null     object
 6   Фібрин2      101 non-null    float64
 7   МНВ2         76 non-null     object
dtypes: float64(1), object(5), str(2)
memory usage: 18.2+ KB

In [5]:
# Далі — що є всередині насправді
for c in МОЇ:
    з = df[c].dropna()
    типи = ', '.join(f'{t.__name__}×{n}' for t, n in з.map(type).value_counts().items())
    print(f'--- {c}')
    print(f'    непорожніх {len(з)} з {len(df)} | унікальних {з.nunique()} | типи: {типи}')
    print(f'    приклади: {[repr(v) for v in з.unique()[:4]]}')
    print()

--- Телефон
    непорожніх 120 з 121 | унікальних 120 | типи: str×97, int×23
    приклади: ["'0958469788 дружина Ганна'", "'0671778486, 0994887663 дружина Оксана'", "'0958768045, чоловік Степан 0951784726'", "'0959819331. дочка Валентина 0960845205'"]

--- Ускладнення
    непорожніх 61 з 121 | унікальних 35 | типи: str×61
    приклади: ["'тромбоз підколінної артерії, гангрена? ТЕЛА? СЛН ГРДС'", "'Респірат дестрес синдром, емфізема легень, СЛН'", "'Респірат дестрес синдром, емфізема легень, СЛН ТІШ'", "'Гострий респіраторний дистрес синдром,ТЕЛА?Прогресуюча серц-леген недос'"]

--- Перебіг
    непорожніх 121 з 121 | унікальних 3 | типи: str×121
    приклади: ["'важкий'", "'серед важ'", "'вкрай важкий '"]

--- Виписка
    непорожніх 120 з 121 | унікальних 90 | типи: datetime×118, str×2
    приклади: ['datetime.datetime(2022, 3, 10, 0, 0)', 'datetime.datetime(2022, 3, 16, 0, 0)', 'datetime.datetime(2022, 1, 18, 0, 0)', 'datetime.datetime(2022, 1, 13, 0, 0)']

--- Ліжко днів
    непорожніх 120 з 121 | унікальних 40 | типи: int×119, str×1
    приклади: ['14', '22', '20', '27']

--- Д-дим1
    непорожніх 59 з 121 | унікальних 48 | типи: int×52, float×5, str×2
    приклади: ['3316', '8000', '183', '3028']

--- Фібрин2
    непорожніх 101 з 121 | унікальних 82 | типи: float×101
    приклади: ['np.float64(2.3)', 'np.float64(3.4)', 'np.float64(3.27)', 'np.float64(4.0)']

--- МНВ2
    непорожніх 76 з 121 | унікальних 51 | типи: float×73, int×2, datetime×1
    приклади: ['239', '1.08', '1.18', '1.07']

### Заповніть паспорт

Для кожного стовпця вкажіть шкалу та **обґрунтування** — одне речення про те,
чому саме ця шкала. Обґрунтування оцінюється, назва шкали сама по собі — ні.

In [6]:
ПАСПОРТ = {
    # 'назва стовпця': ('шкала', 'обґрунтування однією фразою'),
    'Телефон': ('Номінальна', 'Неможливо порівняти за номером і ПІЬ хто кращий'),
   'Ускладнення': ('Номінальна','Неможливо визначити що гірше'),
   'Перебіг': ('Порядкова','Маємо стани важкості але не у математичному вигляді'),
   'Виписка': ('Інтервальна','Різниця між датами має сенс і можна визначити умовно нульову'),
   'Ліжко днів': ('Абсолютна','Розрахунок цілих неподільних одиниць і присутній нуль'),
   'Д-дим1': ('Відношень','Лабораторний показник, є абсолютний 0 і значення можна ділити одне на одне'),
   'Фібрин2': ('Відношень','Лабораторний показник, є абсолютний 0 і значення можна ділити одне на одне'),
   'МНВ2': ('Відношень','Лабораторний показник, є абсолютний 0 і значення можна ділити одне на одне'),
}

for c in МОЇ:
    ПАСПОРТ.setdefault(c, ('', ''))

паспорт_df = pd.DataFrame(
    [(c, ПАСПОРТ[c][0], ПАСПОРТ[c][1]) for c in МОЇ],
    columns=['Стовпець', 'Шкала', 'Обґрунтування'])
паспорт_df

,Стовпець,Шкала,Обґрунтування
0,Телефон,Номінальна,Неможливо порівняти за номером і ПІЬ хто кращий
1,Ускладнення,Номінальна,Неможливо визначити що гірше
2,Перебіг,Порядкова,Маємо стани важкості але не у математичному вигляді
3,Виписка,Інтервальна,Різниця між датами має сенс і можна визначити умовно нул...
4,Ліжко днів,Абсолютна,Розрахунок цілих неподільних одиниць і присутній нуль
5,Д-дим1,Відношень,"Лабораторний показник, є абсолютний 0 і значення можна д..."
6,Фібрин2,Відношень,"Лабораторний показник, є абсолютний 0 і значення можна д..."
7,МНВ2,Відношень,"Лабораторний показник, є абсолютний 0 і значення можна д..."

In [7]:
# --- САМОПЕРЕВІРКА 1 ---
ДОПУСТИМІ = {'номінальна', 'порядкова', 'інтервальна', 'відношень',
             'абсолютна', 'ідентифікатор'}
for c in МОЇ:
    ш, об = ПАСПОРТ[c]
    assert ш.strip().lower() in ДОПУСТИМІ, f'{c}: шкалу «{ш}» не розпізнано'
    assert len(об.strip()) >= 25, f'{c}: обґрунтування закоротке'
print('Самоперевірка 1 пройдена: усі вісім стовпців мають шкалу та обґрунтування.')

Самоперевірка 1 пройдена: усі вісім стовпців мають шкалу та обґрунтування.

---
# Етап 2. Допустимі статистики

Для кожного стовпця обчисліть **тільки те, що дозволяє його шкала**.

* номінальна та ідентифікатор — мода, частоти
* порядкова — додатково медіана та квантилі
* інтервальна — додатково середнє та стандартне відхилення
* відношень і абсолютна — усе, зокрема коефіцієнт варіації

Якщо для стовпця не можна порахувати нічого, крім частот, — так і напишіть.

In [8]:
def допустима_статистика(стовпець, шкала):
    """Повертає словник статистик, дозволених для цієї шкали."""
    з = df[стовпець].dropna()
    р = {'непорожніх': len(з), 'унікальних': з.nunique()}
    ш = шкала.strip().lower()

    р['мода'] = з.mode().tolist()
    р['частоти'] = з.value_counts().to_dict()
    if ш in ('ідентифікатор', 'номінальна'):
        return р
    try:
        р['медіана'] = з.median()
        р['квантилі'] = з.quantile([0.25, 0.5, 0.75]).to_dict()
    except TypeError:
        р['медіана'] = 'Потребує числа'
        р['квантилі'] = 'Потребує числа'
    if ш in ('порядкова'):
        return р
    try:
        р['середнє'] = з.mean()
        р['стандартне відхилення'] = з.std()
    except TypeError:
        р['середнє'] = 'Неможливо обчислити для дати або тексту'
        р['стандартне відхилення'] = 'Неможливо обчислити'
        
    if ш in ('інтервальна'):
        return р
    try:
        р['середнє'] = з.mean()
        р['коефіцієнт варіації'] = (з.std()/р['середнє']) if р['середнє']!=0 else None
    except TypeError:
        р['коефіцієнт варіації'] = 'Неможливо обчислити'
    
    if ш in ('відношень', 'абсолютна'):
        return р
    return р


for c in МОЇ:
    print(f'--- {c}  ({ПАСПОРТ[c][0]})')
    print('   ', допустима_статистика(c, ПАСПОРТ[c][0]))
    print()

--- Телефон  (Номінальна)
    {'непорожніх': 120, 'унікальних': 120, 'мода': [501320598, 503516199, 504118955, 506188479, 634193039, 635060454, 637056709, 675240137, 677611387, 680156464, 680591483, 681960278, 686795965, 688280258, 955939761, 961280845, 964398286, 967464397, 968181378, 969042163, 990370382, 991566979, 992041263, '0503817805, друж Вікторія 0997803704', '0504887781 Марина', '0505529301 сестра Лариса', '0634104751 внучкаАльона ', '0635244106 син Микола', '0637212835, дружт 0956990854', '0637258771, син Сергій 0968413301', '0637613414 дочка Софія', '0638296017невістка', '0638440932, дружина Ганна 0634845263', '0670383004 друж Марія', '0671076177 дочка Дарина', '0671778486, 0994887663 дружина Оксана', '0672022697, невістка Тетяна 0960438581', '0673257192 подруга', '0675795111, дочка 0954432568', '0675996775, син Сергій 0500314503', '06762394249 брат Роман', '0679110285 подруга Зоряна', '072761514 дочка Катерина', '0951331159, друж Марина 0992123636', '0952294866, дочка Дарина 0678360161', '0953197967, друж 0960736087', '0953516768 син Григорій', '0953924196, чол.Володимир 0998982104', '0954754072, дочка Христина 0507547354', '0958469788 дружина Ганна', '0958768045, чоловік Степан 0951784726', '0959819331. дочка Валентина 0960845205', '0959922983 сестра Софія', '0960053051 дочка Наталія', '0960187916. чол Володимир 0999797802', '0961299914 внучка', '0962359534син Віктор', '0962446026чоловік Василь', '0962819539, друж Людмила 0508276116', '0962992398 внук Влад', '0963194893, сестра Катерина 0964948214', '0964502831, друж Марія 0956323373', '0966327926, син 0635154742', '0969974535 дочка Юлія', '0992007009невістка Катерина', '0993228088, син Степан 0954230048', '0995568983, чол Сергій 0679822290', '0997605538 син Микола', '0998073702, дружина Наталія 0998382226', 'брат Олег 0999043163', 'внук Євген 0951100989', 'внук Михайло0632764129', 'внучка Альона 0636643231', 'дочка Валентина 0507425657', 'дочка Ганна 0954851481', 'дочка Ганна 0958195961', 'дочка Ганна 0994262837', 'дочка Дарина 0505753921', 'дочка Лариса 0997567817', 'дочка Людмила 0503327967', 'дочка Людмила 0672713831', 'дочка Людмила 0958179223', 'дочка Олена 0676079113', 'дочка Тетяна 0638861930', 'дочка Тетяна 0961524735', 'дочка Тетяна 0968704151', 'дочка Уляна 0998288983', 'дочка Юлія 0638639848', 'дочка галина 0507002238', 'дружина Катерина 0503022502', 'дружина Марія 0963419082', 'дружина Надія0964985568', 'дружина Оксана 0679360550', 'дружина Оксана 0990499531', 'дружина Христина 0965424744', 'дружина Христина 0993782760', 'дружина Юлія 0950856517', 'дружинаРуслана 0990747776', 'невістка Ганна0965816354', 'невістка Дарина 0635013510', 'невістка Олена 186134069', 'невістка Тетяна 0678792687', 'плем альона 0954366282', 'племінниця Софія 0952056832', 'подруга Ольга 0996450114', 'родич Роман 0998637877', 'сестра Юлія 479672521', 'син 0951520299', 'син Богдан 0632692767', 'син Василь 0992528456', 'син Володимир 0679932157', 'син Віктор 0995165850', 'син Дмитро 0996929844', 'син ОЛлександр0635219803', 'син Юрій 0506942669', 'син Юрій 0968372527', 'син Ярослав 0638421083', 'син Ярослав 0960788203', 'син владислав 0997879432', 'чол Володимир 0503729871'], 'частоти': {'0958469788 дружина Ганна': 1, '0671778486, 0994887663 дружина Оксана': 1, '0958768045, чоловік Степан 0951784726': 1, '0959819331. дочка Валентина 0960845205': 1, '0952294866, дочка Дарина 0678360161': 1, '0959922983 сестра Софія': 1, '0998073702, дружина Наталія 0998382226': 1, '0637258771, син Сергій 0968413301': 1, '0963194893, сестра Катерина 0964948214': 1, '0635244106 син Микола': 1, 504118955: 1, 955939761: 1, 635060454: 1, '0679110285 подруга Зоряна': 1, '0993228088, син Степан 0954230048': 1, 961280845: 1, 990370382: 1, 'син владислав 0997879432': 1, 'син Ярослав 0638421083': 1, '0638440932, дружина Ганна 0634845263': 1, 688280258: 1, 'син Володимир 0679932157': 1, '0675795111, дочка 0954432568': 1, '0966327926, син 0635154742': 1, 'дружина Юлія 0950856517': 1, '0675996775, син Сергій 0500314503': 1, '0953924196, чол.Володимир 0998982104': 1, '0954754072, дочка Христина 0507547354': 1, 506188479: 1, 'дочка Тетяна 0638861930': 1, '0995568983, чол Сергій 0679822290': 1, '0672022697, невістка Тетяна 0960438581': 1, '0964502831, друж Марія 0956323373': 1, '0951331159, друж Марина 0992123636': 1, '0637212835, дружт 0956990854': 1, '0960187916. чол Володимир 0999797802': 1, 'дочка Тетяна 0961524735': 1, '0953197967, друж 0960736087': 1, '0962819539, друж Людмила 0508276116': 1, '0503817805, друж Вікторія 0997803704': 1, 'дочка Уляна 0998288983': 1, 'дочка Людмила 0958179223': 1, 'син Юрій 0968372527': 1, 'брат Олег 0999043163': 1, 'чол Володимир 0503729871': 1, 'дочка Олена 0676079113': 1, 'син ОЛлександр0635219803': 1, 'дочка Юлія 0638639848': 1, 'син Богдан 0632692767': 1, 'дружина Надія0964985568': 1, 'дочка Людмила 0503327967': 1, 'невістка Ганна0965816354': 1, 677611387: 1, '0671076177 дочка Дарина': 1, 'син 0951520299': 1, 503516199: 1, 964398286: 1, 967464397: 1, 634193039: 1, 991566979: 1, 686795965: 1, 637056709: 1, 680156464: 1, 501320598: 1, 969042163: 1, 681960278: 1, '0638296017невістка': 1, 992041263: 1, 675240137: 1, 680591483: 1, 968181378: 1, '0673257192 подруга': 1, '0637613414 дочка Софія': 1, '0960053051 дочка Наталія': 1, '0997605538 син Микола': 1, '072761514 дочка Катерина': 1, '06762394249 брат Роман': 1, '0969974535 дочка Юлія': 1, '0634104751 внучкаАльона ': 1, '0962359534син Віктор': 1, '0962446026чоловік Василь': 1, '0992007009невістка Катерина': 1, '0504887781 Марина': 1, '0670383004 друж Марія': 1, '0505529301 сестра Лариса': 1, '0962992398 внук Влад': 1, '0961299914 внучка': 1, '0953516768 син Григорій': 1, 'плем альона 0954366282': 1, 'дочка Ганна 0994262837': 1, 'дочка Тетяна 0968704151': 1, 'дружина Христина 0993782760': 1, 'дочка галина 0507002238': 1, 'невістка Дарина 0635013510': 1, 'син Віктор 0995165850': 1, 'дружина Катерина 0503022502': 1, 'дружина Марія 0963419082': 1, 'родич Роман 0998637877': 1, 'внук Михайло0632764129': 1, 'дружина Оксана 0679360550': 1, 'невістка Тетяна 0678792687': 1, 'племінниця Софія 0952056832': 1, 'син Ярослав 0960788203': 1, 'внук Євген 0951100989': 1, 'син Дмитро 0996929844': 1, 'внучка Альона 0636643231': 1, 'сестра Юлія 479672521': 1, 'дочка Людмила 0672713831': 1, 'дочка Валентина 0507425657': 1, 'подруга Ольга 0996450114': 1, 'дочка Ганна 0954851481': 1, 'дочка Ганна 0958195961': 1, 'дочка Дарина 0505753921': 1, 'дружина Оксана 0990499531': 1, 'дружина Христина 0965424744': 1, 'син Василь 0992528456': 1, 'син Юрій 0506942669': 1, 'дружинаРуслана 0990747776': 1, 'невістка Олена 186134069': 1, 'дочка Лариса 0997567817': 1}}

--- Ускладнення  (Номінальна)
    {'непорожніх': 61, 'унікальних': 35, 'мода': ['Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок'], 'частоти': {'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок': 14, 'ГРДС ': 5, 'Прогресуюча серц-леген недос .Набряк легень . Сладж синдром': 3, 'Гострий респіраторний дистрес синдром,ТЕЛА?Прогресуюча серц-леген недос': 2, 'ГРДС .ТЕЛА': 2, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок. Шокові нирки.Некронефроз': 2, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок. ТЕЛА?': 2, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок. ': 2, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок.Сладж синдром': 2, 'Прогресуюча серц-леген недос. Токсико-бактер шок. Набряк легень. ДВЗ-синд': 2, 'тромбоз підколінної артерії, гангрена? ТЕЛА? СЛН ГРДС': 1, 'Респірат дестрес синдром, емфізема легень, СЛН': 1, 'Респірат дестрес синдром, емфізема легень, СЛН ТІШ': 1, 'Гострий респіраторний дистрес синдром,ТЕЛА?Прогресуюча серц-леген недос.Септичний шок. Бактеріальна деструкція легень': 1, 'Гострий респіраторний дистрес синдром,ТЕЛА?Прогресуюча серц-леген недос. Гостре порушення мозкового кровообігу': 1, 'Гострий респіраторний дистрес синдром. Прогресуюча серц-леген недос. Сладж синдром .Гостра емфізема легень.Вірусний енцефаліт': 1, 'Гострий респіраторний дистрес синдром.Гострий некротичний нефроз. Набряк легень': 1, 'Гострий респіраторний дистрес синдром. Прогресуюча серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок': 1, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок.Гепатит': 1, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.': 1, 'ГРДС .ТЕЛА.Поліорганна недостатність ': 1, 'ГРДС.Інфаркт.ТЕЛА': 1, 'ГРДС. ТЕЛА.Набряк легень': 1, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Токсико-інфекційний шок. Набряк легень': 1, 'Прогресуюча серц-леген недос .Набряк легень . Мускатна печінка': 1, 'Гострий респіраторний дистрес синдром. Гостра серц-леген недос .Гостра емфізема легень.Сладж синдром': 1, 'Прогресуюча серц-леген недос .Набряк легень . Сладж синдром. Гідроперекард . Двобічний гідроторакс ': 1, 'Прогресуюча серц-леген недос .Набряк легень .Вогнищева емфізема легень .Сладж синдром': 1, 'Прогресуюча серц-леген недос .Набряк легень .Гідроперекард 300мл. Двобічний гідроторакс 2л': 1, 'Набряк головного мозку . Набряк легень. Ішемічний інсульт': 1, 'Гострий коронарний синдром. Гострий інфарк міокарда. ТЕЛА?': 1, 'Прогресуюча легенева недос. Набряк легень. ДВЗ синд.': 1, 'Прогресуюча серц-леген недос. Вогнищева емфізема легень. Набряк легень. Мускатна печінка': 1, 'Тромбоз дрібних гілок легенової артерії. Набряк легень': 1, 'Тромбоз дрібних гілок легенової артерії. Набряк легень.': 1}}

--- Перебіг  (Порядкова)
    {'непорожніх': 121, 'унікальних': 3, 'мода': ['важкий'], 'частоти': {'важкий': 90, 'серед важ': 30, 'вкрай важкий ': 1}, 'медіана': 'Потребує числа', 'квантилі': 'Потребує числа'}

--- Виписка  (Інтервальна)
    {'непорожніх': 120, 'унікальних': 90, 'мода': [datetime.datetime(2021, 9, 7, 0, 0), datetime.datetime(2021, 9, 11, 0, 0), datetime.datetime(2021, 9, 15, 0, 0), datetime.datetime(2021, 11, 19, 0, 0), datetime.datetime(2022, 4, 6, 0, 0), datetime.datetime(2022, 6, 6, 0, 0)], 'частоти': {datetime.datetime(2021, 11, 19, 0, 0): 3, datetime.datetime(2021, 9, 7, 0, 0): 3, datetime.datetime(2021, 9, 15, 0, 0): 3, datetime.datetime(2021, 9, 11, 0, 0): 3, datetime.datetime(2022, 4, 6, 0, 0): 3, datetime.datetime(2022, 6, 6, 0, 0): 3, datetime.datetime(2022, 1, 18, 0, 0): 2, datetime.datetime(2022, 5, 11, 0, 0): 2, datetime.datetime(2022, 5, 13, 0, 0): 2, datetime.datetime(2021, 11, 16, 0, 0): 2, datetime.datetime(2022, 5, 12, 0, 0): 2, datetime.datetime(2021, 11, 25, 0, 0): 2, datetime.datetime(2022, 4, 8, 0, 0): 2, datetime.datetime(2022, 4, 2, 0, 0): 2, datetime.datetime(2022, 4, 27, 0, 0): 2, datetime.datetime(2022, 4, 22, 0, 0): 2, datetime.datetime(2022, 3, 24, 0, 0): 2, datetime.datetime(2022, 4, 24, 0, 0): 2, datetime.datetime(2022, 4, 5, 0, 0): 2, datetime.datetime(2021, 12, 24, 0, 0): 2, datetime.datetime(2021, 6, 9, 0, 0): 2, datetime.datetime(2022, 2, 24, 0, 0): 2, datetime.datetime(2022, 4, 9, 0, 0): 2, datetime.datetime(2022, 5, 3, 0, 0): 2, datetime.datetime(2022, 3, 10, 0, 0): 1, datetime.datetime(2022, 3, 16, 0, 0): 1, datetime.datetime(2022, 1, 13, 0, 0): 1, datetime.datetime(2022, 3, 11, 0, 0): 1, datetime.datetime(2021, 12, 26, 0, 0): 1, datetime.datetime(2022, 5, 28, 0, 0): 1, datetime.datetime(2021, 12, 23, 0, 0): 1, datetime.datetime(2021, 12, 18, 0, 0): 1, datetime.datetime(2021, 11, 30, 0, 0): 1, datetime.datetime(2021, 9, 2, 0, 0): 1, datetime.datetime(2021, 9, 10, 0, 0): 1, datetime.datetime(2021, 9, 14, 0, 0): 1, datetime.datetime(2021, 10, 27, 0, 0): 1, datetime.datetime(2021, 7, 3, 0, 0): 1, datetime.datetime(2021, 10, 20, 0, 0): 1, datetime.datetime(2021, 12, 31, 0, 0): 1, datetime.datetime(2021, 7, 9, 0, 0): 1, datetime.datetime(2021, 6, 10, 0, 0): 1, datetime.datetime(2021, 6, 5, 0, 0): 1, datetime.datetime(2021, 9, 25, 0, 0): 1, datetime.datetime(2021, 9, 28, 0, 0): 1, datetime.datetime(2022, 4, 19, 0, 0): 1, datetime.datetime(2022, 6, 17, 0, 0): 1, datetime.datetime(2022, 4, 14, 0, 0): 1, datetime.datetime(2021, 12, 1, 0, 0): 1, datetime.datetime(2021, 10, 23, 0, 0): 1, datetime.datetime(2021, 7, 2, 0, 0): 1, datetime.datetime(2021, 4, 27, 0, 0): 1, datetime.datetime(2021, 12, 16, 0, 0): 1, datetime.datetime(2021, 7, 30, 0, 0): 1, datetime.datetime(2021, 7, 21, 0, 0): 1, datetime.datetime(2021, 7, 28, 0, 0): 1, datetime.datetime(2022, 4, 16, 0, 0): 1, datetime.datetime(2022, 4, 26, 0, 0): 1, '24.024.2021': 1, '20.24.2021': 1, datetime.datetime(2022, 4, 12, 0, 0): 1, datetime.datetime(2022, 3, 1, 0, 0): 1, datetime.datetime(2022, 3, 29, 0, 0): 1, datetime.datetime(2022, 5, 2, 0, 0): 1, datetime.datetime(2022, 6, 22, 0, 0): 1, datetime.datetime(2022, 3, 4, 0, 0): 1, datetime.datetime(2022, 3, 2, 0, 0): 1, datetime.datetime(2022, 6, 4, 0, 0): 1, datetime.datetime(2022, 4, 28, 0, 0): 1, datetime.datetime(2022, 3, 30, 0, 0): 1, datetime.datetime(2022, 5, 6, 0, 0): 1, datetime.datetime(2022, 1, 6, 0, 0): 1, datetime.datetime(2022, 2, 9, 0, 0): 1, datetime.datetime(2022, 2, 17, 0, 0): 1, datetime.datetime(2022, 5, 22, 0, 0): 1, datetime.datetime(2022, 5, 29, 0, 0): 1, datetime.datetime(2022, 5, 18, 0, 0): 1, datetime.datetime(2022, 4, 20, 0, 0): 1, datetime.datetime(2022, 6, 2, 0, 0): 1, datetime.datetime(2022, 5, 20, 0, 0): 1, datetime.datetime(2022, 5, 15, 0, 0): 1, datetime.datetime(2022, 5, 1, 0, 0): 1, datetime.datetime(2022, 4, 30, 0, 0): 1, datetime.datetime(2022, 4, 29, 0, 0): 1, datetime.datetime(2022, 4, 13, 0, 0): 1, datetime.datetime(2022, 3, 14, 0, 0): 1, datetime.datetime(2022, 2, 14, 0, 0): 1, datetime.datetime(2022, 5, 21, 0, 0): 1, datetime.datetime(2022, 5, 7, 0, 0): 1, datetime.datetime(2022, 5, 5, 0, 0): 1}, 'медіана': 'Потребує числа', 'квантилі': 'Потребує числа', 'середнє': 'Неможливо обчислити для дати або тексту', 'стандартне відхилення': 'Неможливо обчислити'}

--- Ліжко днів  (Абсолютна)
    {'непорожніх': 120, 'унікальних': 40, 'мода': [10], 'частоти': {10: 12, 8: 8, 17: 7, 12: 6, 19: 6, 3: 6, 14: 5, 20: 5, 15: 5, 7: 4, 16: 4, 22: 3, 18: 3, 37: 3, 11: 3, 21: 3, 31: 3, 27: 2, 28: 2, 9: 2, 29: 2, 13: 2, 39: 2, 25: 2, 5: 2, 24: 2, 6: 2, 4: 2, '9(5 у реан)': 1, 65: 1, 35: 1, 30: 1, 48: 1, 36: 1, 32: 1, 73: 1, 33: 1, 79: 1, 1: 1, 23: 1}, 'медіана': 'Потребує числа', 'квантилі': 'Потребує числа', 'середнє': 'Неможливо обчислити для дати або тексту', 'стандартне відхилення': 'Неможливо обчислити', 'коефіцієнт варіації': 'Неможливо обчислити'}

--- Д-дим1  (Відношень)
    {'непорожніх': 59, 'унікальних': 48, 'мода': [10000], 'частоти': {10000: 11, 364: 2, 3316: 1, 8000: 1, 183: 1, 3028: 1, 1100: 1, 238: 1, 972: 1, 1105: 1, 968: 1, 645.98: 1, 145.8: 1, '4442; 1084 ': 1, '480;': 1, 796.19: 1, 5044: 1, 700: 1, 3250: 1, 839: 1, 206: 1, 358: 1, 186: 1, 1727: 1, 146: 1, 402: 1, 1004: 1, 1581: 1, 3223: 1, 543: 1, 484: 1, 1015.32: 1, 4148: 1, 2253: 1, 3750: 1, 5556: 1, 3782: 1, 1099: 1, 1000: 1, 1344: 1, 4000: 1, 1771: 1, 1258: 1, 3.47: 1, 7144: 1, 3497: 1, 9353: 1, 1436: 1}, 'медіана': 'Потребує числа', 'квантилі': 'Потребує числа', 'середнє': 'Неможливо обчислити для дати або тексту', 'стандартне відхилення': 'Неможливо обчислити', 'коефіцієнт варіації': 'Неможливо обчислити'}

--- Фібрин2  (Відношень)
    {'непорожніх': 101, 'унікальних': 82, 'мода': [4.0], 'частоти': {4.0: 4, 3.0: 3, 4.21: 3, 3.55: 3, 3.12: 2, 2.66: 2, 7.0: 2, 5.0: 2, 3.1: 2, 2.59: 2, 2.52: 2, 3.6: 2, 4.6: 2, 2.08: 2, 2.3: 1, 3.4: 1, 3.27: 1, 3.37: 1, 2.4: 1, 3.18: 1, 2.2: 1, 2.53: 1, 6.6: 1, 2.14: 1, 3.92: 1, 1.7: 1, 8.88: 1, 7.98: 1, 5.1: 1, 4.2: 1, 3.2: 1, 2.9: 1, 7.77: 1, 5.55: 1, 4.66: 1, 4.44: 1, 2.22: 1, 2.55: 1, 3.65: 1, 2.36: 1, 1.5: 1, 5.37: 1, 7.5: 1, 5.2: 1, 4.55: 1, 4.3: 1, 11.1: 1, 2.6: 1, 2.24: 1, 2.7: 1, 4.88: 1, 6.66: 1, 6.16: 1, 8.87: 1, 2.35: 1, 5.05: 1, 5.11: 1, 3.09: 1, 5.01: 1, 7.22: 1, 4.53: 1, 8.01: 1, 5.47: 1, 3.76: 1, 8.47: 1, 2.68: 1, 3.75: 1, 6.7: 1, 6.05: 1, 7.55: 1, 0.99: 1, 4.73: 1, 4.08: 1, 2.93: 1, 3.33: 1, 5.07: 1, 2.43: 1, 4.68: 1, 5.06: 1, 4.42: 1, 4.36: 1, 2.46: 1}, 'медіана': np.float64(3.92), 'квантилі': {0.25: 2.7, 0.5: 3.92, 0.75: 5.05}, 'середнє': np.float64(4.220396039603961), 'стандартне відхилення': np.float64(1.884609201289264), 'коефіцієнт варіації': np.float64(0.44654795038290157)}

--- МНВ2  (Відношень)
    {'непорожніх': 76, 'унікальних': 51, 'мода': [1.24], 'частоти': {1.24: 4, 1.18: 3, 1.09: 3, 1.02: 3, 0.97: 3, 1.27: 3, 1.19: 2, 1.15: 2, 1.04: 2, 1.26: 2, 1.46: 2, 1.21: 2, 1.32: 2, 1.13: 2, 0.92: 2, 1.2: 2, 1.39: 2, 1.38: 2, 239: 1, 1.08: 1, 1.07: 1, 2.18: 1, datetime.datetime(2015, 1, 1, 0, 0): 1, 0.85: 1, 0.98: 1, 1: 1, 1.3: 1, 1.22: 1, 1.53: 1, 0.94: 1, 2.05: 1, 1.17: 1, 1.8: 1, 0.87: 1, 1.01: 1, 1.51: 1, 1.33: 1, 1.03: 1, 1.31: 1, 1.43: 1, 0.08: 1, 1.6: 1, 1.92: 1, 1.16: 1, 1.14: 1, 1.5: 1, 1.1: 1, 1.66: 1, 1.44: 1, 1.62: 1, 2.29: 1}, 'медіана': 'Потребує числа', 'квантилі': 'Потребує числа', 'середнє': 'Неможливо обчислити для дати або тексту', 'стандартне відхилення': 'Неможливо обчислити', 'коефіцієнт варіації': 'Неможливо обчислити'}

---
# Етап 3. Три безглузді числа

`df.describe()` порахує статистики для всього, що схоже на число. Частина цих чисел
не має жодного змісту.

Знайдіть **щонайменше три** такі числа у своєму наборі: обчисліть їх, а потім
поясніть, чому кожне з них безглузде.

In [9]:
df[МОЇ].describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Телефон,120,120,0958469788 дружина Ганна,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ускладнення,61,35,Гострий респіраторний дистрес синдром. Гостра серц-леген...,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Перебіг,121,3,важкий,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Виписка,120,90,2021-11-19 00:00:00,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Ліжко днів,120.0,40.0,10.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Д-дим1,59.0,48.0,10000.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Фібрин2,101.0,NaN,NaN,NaN,4.220396,1.884609,0.99,2.7,3.92,5.05,11.1
МНВ2,76.0,51.0,1.24,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
БЕЗГЛУЗДІ = [
    # ('стовпець', 'яка статистика', значення, 'чому це число нічого не означає'),
    ('Телефон', 'freq', 1, 'Частота появи номеру людини завжди буде 1.'),
    ('Д-дим1', 'top', 10000.0, 'Шукати моду для лабораторного показника сенсу немає.'),
    ('МНВ2', 'freq', 4.0, 'Для частоти потрібне середнє відхилення, а порахувано через наявність дати.')
]

assert len(БЕЗГЛУЗДІ) >= 3, 'Потрібно щонайменше три приклади'
pd.DataFrame(БЕЗГЛУЗДІ, columns=['Стовпець', 'Статистика', 'Значення', 'Чому безглузде'])

,Стовпець,Статистика,Значення,Чому безглузде
0,Телефон,freq,1.0,Частота появи номеру людини завжди буде 1.
1,Д-дим1,top,10000.0,Шукати моду для лабораторного показника сенсу немає.
2,МНВ2,freq,4.0,"Для частоти потрібне середнє відхилення, а порахувано че..."

---
# Етап 4. Міра зв'язку для вашої пари

Для двох змінних вашого варіанта треба оцінити зв'язок. Міру обирає **пара шкал**,
а не зручність:

| Поєднання шкал | Міра |
|---|---|
| відношень × відношень | кореляція Пірсона |
| порядкова × порядкова | рангова кореляція Спірмена |
| номінальна × номінальна | χ² та коефіцієнт Крамера (V) |
| відношень × бінарна номінальна | точковий бісеріальний коефіцієнт |
| номінальна × порядкова | коефіцієнт Крамера (V) |

Обґрунтуйте вибір, обчисліть міру й поясніть результат. Окремо покажіть, **що
станеться**, якщо застосувати Пірсона там, де він недопустимий, — і чому отримане
число не можна інтерпретувати.

In [11]:
A, B = В['пара']
print('Ваша пара:', A, '×', B)
print()
print(f'{A}: шкала —', ПАСПОРТ.get(A, ('не у вашому списку',))[0] or '(визначте самостійно)')
print(f'{B}: шкала —', ПАСПОРТ.get(B, ('не у вашому списку',))[0] or '(визначте самостійно)')
print()
print(df[[A, B]].head(6).to_string())

Ваша пара: ступінь КТ × ЛН

ступінь КТ: шкала — не у вашому списку
ЛН: шкала — не у вашому списку

  ступінь КТ      ЛН
0    сердній  ІІІ-IV
1   середній  ІІ-ІІІ
2  критичний      ІІ
3  критичний  ІІІ-IV
4        NaN  ІІ-ІІІ
5   середній  ІІ-ІІІ

In [12]:
from scipy import stats
ОБРАНА_МІРА = 'рангова кореляція Спірмена'        # напишіть назву міри
ЧОМУ_САМЕ_ВОНА = 'ступінь КТ та ЛН вимірюються в порядковій шкалі. Для поєднання "порядкова × порядкова" використовується саме рангова кореляція Спірмена.'     # одне-два речення

assert ОБРАНА_МІРА and len(ЧОМУ_САМЕ_ВОНА) >= 40, 'Заповніть обидва поля'

# ваш код: обчисліть обрану міру
KT = {
    'легкий': 1, 
    'сердній': 2,  
    'середній': 2, 
    'важкий': 3, 
    'критичний': 4
}
LN = {
    'І': 1, 
    'І-ІІ': 1.5, 
    'ІІ': 2, 
    'ІІ-ІІІ': 2.5, 
    'ІІІ': 3, 
    'ІІІ-IV': 3.5, 
    'IV': 4
}
pair = df[[A, B]].dropna().copy()
pair[A] = pair[A].astype(str).str.strip().map(KT)
pair[B] = pair[B].astype(str).str.strip().map(LN)
pair = pair.dropna()
correlation, p_value = stats.spearmanr(pair[A], pair[B])
print(f"Коефіцієнт Спірмена: {correlation:.4f}")

Коефіцієнт Спірмена: 0.5738

In [13]:
# Тепер — контрприклад: застосуйте кореляцію Пірсона незалежно від шкал
# і поясніть, чому отримане число не можна використовувати.
correlation2, p_value2 = stats.pearsonr(pair[A], pair[B])
print(f"Коефіцієнт Пірсона: {correlation2:.4f}")

print("Коефіцієнт Пірсона вимагає шкали відношень та лінійної залежності."
      "Він вважає, що різниця у важкості між ІІ та ІІІ ступенем абсолютно така ж,"
      "як між І та ІІ. Для медичних порядкових шкал це хибне припущення.")

Коефіцієнт Пірсона: 0.5530
Коефіцієнт Пірсона вимагає шкали відношень та лінійної залежності.Він вважає, що різниця у важкості між ІІ та ІІІ ступенем абсолютно така ж,як між І та ІІ. Для медичних порядкових шкал це хибне припущення.

---
# Етап 5. Підготовка змінних до моделі

Шкала визначає не лише статистику, а й спосіб кодування.

| Шкала | Як готують до моделі |
|---|---|
| Номінальна | one-hot кодування; порядок категорій не вводять |
| Порядкова | впорядкована категорія або цілі коди із **заданим** порядком |
| Інтервальна | стандартизація; для дат — перехід до тривалостей |
| Відношень | нормалізація або стандартизація; можливе логарифмування |
| Ідентифікатор | у модель не беруть узагалі |

Для кожного свого стовпця вкажіть спосіб підготовки — і **виконайте його**
щонайменше для трьох стовпців різних шкал.

In [14]:
ПІДГОТОВКА = {
    # 'стовпець': 'спосіб і коротке обґрунтування',
    'Телефон': 'Номінальна (ідентифікатор): не несе цінності, видаляється з датасету.',
    'Ускладнення': 'Номінальна: застосовується One-Hot Encoding.',
    'Перебіг': 'Порядкова: кодування цілими числами зі збереженням важкості.',
    'Виписка': 'Інтервальна: перетворення дати на тривалість.',
    'Ліжко днів': 'Абсолютна: стандартизація або нормалізація.',
    'Д-дим1': 'Відношень: очищення від текстового сміття, заповнення пропусків та стандартизація.',
    'Фібрин2': 'Відношень: заповнення пропусків та стандартизація.',
    'МНВ2': 'Відношень: очищення від сміття, заповнення пропусків та стандартизація.'
}
for c in МОЇ:
    ПІДГОТОВКА.setdefault(c, '')

pd.DataFrame([(c, ПАСПОРТ[c][0], ПІДГОТОВКА[c]) for c in МОЇ],
             columns=['Стовпець', 'Шкала', 'Як готуємо'])

,Стовпець,Шкала,Як готуємо
0,Телефон,Номінальна,"Номінальна (ідентифікатор): не несе цінності, видаляєтьс..."
1,Ускладнення,Номінальна,Номінальна: застосовується One-Hot Encoding.
2,Перебіг,Порядкова,Порядкова: кодування цілими числами зі збереженням важко...
3,Виписка,Інтервальна,Інтервальна: перетворення дати на тривалість.
4,Ліжко днів,Абсолютна,Абсолютна: стандартизація або нормалізація.
5,Д-дим1,Відношень,"Відношень: очищення від текстового сміття, заповнення пр..."
6,Фібрин2,Відношень,Відношень: заповнення пропусків та стандартизація.
7,МНВ2,Відношень,"Відношень: очищення від сміття, заповнення пропусків та ..."

In [15]:
# ваш код: реалізуйте підготовку для трьох стовпців різних шкал
# 1 Номінальна ('Ускладнення')
ускладнення_ohe = pd.get_dummies(df['Ускладнення'].astype(str).str.strip(), prefix = "Ускл")
ускладнення_ohe = ускладнення_ohe.iloc[:, :4]

# 2 Відношень ('Фібрин2')
fibr_mean = df['Фібрин2'].mean()
fibr_std = df['Фібрин2'].std()
df['Фібрин2_z_score'] = (df['Фібрин2'] - fibr_mean) / fibr_std

# 3 Порядкова ('Перебіг')
perebig_map = {
    'серед важ': 1, 
    'важкий': 2, 
    'вкрай важкий': 3
}
df['Перебіг_num'] = df['Перебіг'].astype(str).str.strip().map(perebig_map)

result = pd.concat([
    df[['Фібрин2', 'Фібрин2_z_score','Перебіг', 'Перебіг_num']], 
    ускладнення_ohe,
], axis=1)

result.head()

,Фібрин2,Фібрин2_z_score,Перебіг,Перебіг_num,Ускл_ГРДС,Ускл_ГРДС .ТЕЛА,Ускл_ГРДС .ТЕЛА.Поліорганна недостатність,Ускл_ГРДС. ТЕЛА.Набряк легень
0,2.30,-1.018989,важкий,2,False,False,False,False
1,3.40,-0.435314,важкий,2,False,False,False,False
2,3.27,-0.504293,важкий,2,False,False,False,False
3,4.00,-0.116945,важкий,2,False,False,False,False
4,3.37,-0.451232,важкий,2,False,False,False,False

**Перед нормалізацією** обов'язково перевірте варіативність. Стовпець, у якому
всі значення однакові, дасть нуль у знаменнику — і мовчазний `NaN` замість помилки.

In [16]:
for c in МОЇ:
    з = pd.to_numeric(df[c], errors='coerce').dropna()
    if len(з) and з.nunique() == 1:
        print(f'УВАГА: {c} — сталий стовпець, нормалізація дасть ділення на нуль')
    elif len(з) and з.max() == з.min():
        print(f'УВАГА: {c} — max дорівнює min')
print('Перевірку варіативності виконано.')

Перевірку варіативності виконано.

In [17]:
# --- САМОПЕРЕВІРКА 2 ---
assert all(len(ПІДГОТОВКА[c].strip()) >= 15 for c in МОЇ), \
    'Для кожного стовпця вкажіть спосіб підготовки'
assert len(БЕЗГЛУЗДІ) >= 3, 'Етап 3 не завершено'
print('Самоперевірка 2 пройдена.')

Самоперевірка 2 пройдена.

---
# Етап 6. Виправлення чужого аналізу

Відкрийте файл **`ЛР3_помилковий_аналіз.ipynb`**. Це звіт, який виконується
без жодної помилки й містить десять хибних місць.

Для кожного з десяти заповніть рядок нижче:

* **розділ** — номер розділу звіту;
* **що не так** — яка шкала порушена або яке припущення хибне;
* **чому число неправильне** — що саме воно означає насправді;
* **як правильно** — коректний варіант або обґрунтована відмова від показника.

In [18]:
ВИПРАВЛЕННЯ = [
    # (розділ, 'що не так', 'чому число неправильне', 'як правильно'),
    (1, 'Результат лікування', 
     'Середнє арифметичне для категорій "помер" і "жив" не має математичного сенсу.', 
     'Треба рахувати моду або відсоток тих, хто вижив, і тих, хто помер через value_counts().'),
    
    (2, 'Дублювання категорій.', 
     'У висновку сказано про 4 статі, хоча насправді їх 2. Це сталося через відсутність стандартизації тексту ("ж" і "жін", "ч" і "чол").', 
     'Спочатку потрібно очистити дані: замінити "жін" на "ж", а "чол" на "ч", і лише потім рахувати частоти.'),
    
    (3, 'Брудні дані (Ступінь КТ).', 
     '1. для порядкової шкали не можна рахувати середнє, бо відстані між ступенями нерівні. 2. через помилки в словах порядок збився і функція просто посортувала дані за алфавітом.', 
     'Очистити текст, закодувати словником зі збереженням ієрархії, і порахувати медіану.'),
    
    (4, 'Втрата даних при перетворенні типів (КТ у %).', 
     'Команда to_numeric(errors="coerce") перетворила на NaN усі записи з діапазонами, залишивши лише поодинокі числа, що сильно викривило середнє.', 
     'Потрібно написати функцію, яка витягує числа з діапазону і бере їхнє середнє.'),
    
    (5, 'Помилка розмірності.', 
     'Сатурація 0.9% означає смерть. Хтось ввів у відсотках. Це спотворило мінімум і, як наслідок, середнє.', 
     'Усі значення, які менші за за 10, потрібно помножити на 100 перед аналізом.'),
    
    (6, 'Інтервальна шкала (Дати поступлення).', 
     'Коефіцієнт варіації можна рахувати лише для шкал відношень. Дата — це інтервальна шкала без абсолютного нуля, тому вона створює ілюзію стабільності.', 
     'Для дат коефіцієнт варіації рахувати не можна. Можна оцінити стандартне відхилення.'),
    
    (7, 'Порушення умов кореляції Пірсона.', 
     'Пірсон вимагає двох шкал відношень з лінійною залежністю. Застосовувати його до категорій стать і смерть не можна.', 
     'Для двох номінальних ознак потрібно використовувати коефіцієнт Крамера.'),
    
    (8, 'Ділення на нуль.', 
     'У стовпці ФЕРИТ2 і інших бракує даних або всі значення однакові. Знаменник стає нулем, що генерує NaN.', 
     'Перед нормалізацією перевірити стовпці на варіативність і виключити ті, де min == max.'),
    
    (9, 'Хибне видалення пропусків.', 
     'Оскільки в медичних даних багато пропусків, dropna() видалив усі рядки, бо в кожному пацієнті бракувало хоч однієї клітинки.', 
     'Спочатку видалити стовпці, де є хоча б половина пропусків, а в решті — заповнити пропуски медіаною.'),
    
    (10, 'Витік даних.', 
     'Дата розтину відбувається лише тоді, коли пацієнт помер. Використовувати її як предиктор — це намагатися "передбачити" подію за наслідком, який настав після неї.', 
     'Перед навчанням моделі з датасету треба видалити всі змінні, які з\'являються після того, як стався цільовий результат.')
]

assert len(ВИПРАВЛЕННЯ) == 10, f'Знайдено {len(ВИПРАВЛЕННЯ)} помилок із 10'
for р in ВИПРАВЛЕННЯ:
    assert len(р) == 4 and all(str(x).strip() for x in р), 'Заповніть усі чотири поля'
    assert len(str(р[2])) >= 30 and len(str(р[3])) >= 25, 'Пояснення закороткі'

pd.DataFrame(ВИПРАВЛЕННЯ, columns=['Розділ', 'Що не так', 'Чому число неправильне', 'Як правильно'])

,Розділ,Що не так,Чому число неправильне,Як правильно
0,1,Результат лікування,"Середнє арифметичне для категорій ""помер"" і ""жив"" не має...","Треба рахувати моду або відсоток тих, хто вижив, і тих, ..."
1,2,Дублювання категорій.,"У висновку сказано про 4 статі, хоча насправді їх 2. Це ...","Спочатку потрібно очистити дані: замінити ""жін"" на ""ж"", ..."
2,3,Брудні дані (Ступінь КТ).,"1. для порядкової шкали не можна рахувати середнє, бо ві...","Очистити текст, закодувати словником зі збереженням ієра..."
3,4,Втрата даних при перетворенні типів (КТ у %).,"Команда to_numeric(errors=""coerce"") перетворила на NaN у...","Потрібно написати функцію, яка витягує числа з діапазону..."
4,5,Помилка розмірності.,Сатурація 0.9% означає смерть. Хтось ввів у відсотках. Ц...,"Усі значення, які менші за за 10, потрібно помножити на ..."
5,6,Інтервальна шкала (Дати поступлення).,Коефіцієнт варіації можна рахувати лише для шкал відноше...,Для дат коефіцієнт варіації рахувати не можна. Можна оці...
6,7,Порушення умов кореляції Пірсона.,Пірсон вимагає двох шкал відношень з лінійною залежністю...,Для двох номінальних ознак потрібно використовувати коеф...
7,8,Ділення на нуль.,У стовпці ФЕРИТ2 і інших бракує даних або всі значення о...,Перед нормалізацією перевірити стовпці на варіативність ...
8,9,Хибне видалення пропусків.,"Оскільки в медичних даних багато пропусків, dropna() вид...","Спочатку видалити стовпці, де є хоча б половина пропускі..."
9,10,Витік даних.,"Дата розтину відбувається лише тоді, коли пацієнт помер....",Перед навчанням моделі з датасету треба видалити всі змі...

### Виправте щонайменше три помилки в коді

Оберіть три з десяти та покажіть правильне обчислення поруч із неправильним.

In [19]:
# ваш код: три правильні обчислення замість хибних
# Rozpodil 1
result = df['помер/жив'].value_counts(normalize=True) * 100
print(f"Вижили: {result[2]:.1f}%\nПомерли: {result[1]:.1f}%")
print()
# Rozpodil 2
clean_sex = df['Стать'].astype(str).str.strip().str.lower().str[0]
print("Розподіл статей:")
print(clean_sex.value_counts())
print()
# Rozpodil 5
spo2 = df['spO2 без дот'].copy()
spo2 = spo2.apply(lambda x: x * 100 if x < 10 else x)
print(f"Справжній мінімум сатурації: {spo2.min()}%")

Вижили: 49.6%
Померли: 50.4%

Розподіл статей:
Стать
ж    75
ч    46
Name: count, dtype: int64

Справжній мінімум сатурації: 50.0%

---
# Етап 7. Висновки та індивідуальне питання

In [20]:
ВИСНОВКИ = [
    # три висновки, кожен — повне речення про ваші дані, а не загальна фраза
    "У медичному наборі даних є дуже багато порожніх клітинок у лабораторних аналізах, тому перед аналізом ці пропуски треба заповнити середніми значеннями.",
    "Через ручне введення тексту в колонках зі статтю та результатами КТ виникло багато помилок і зайвих пробілів, тому такі дані не можна аналізувати без очищення.",
    "Рахувати звичайне середнє значення або лінійну кореляцію для текстових категорій не можна, бо комп'ютер не розуміє медичної логіки і видає числа, які не мають жодного фізичного сенсу."
]
assert len(ВИСНОВКИ) >= 3 and all(len(в) >= 60 for в in ВИСНОВКИ), \
    'Потрібні три змістовні висновки'
for i, в in enumerate(ВИСНОВКИ, 1):
    print(f'{i}. {в}')

1. У медичному наборі даних є дуже багато порожніх клітинок у лабораторних аналізах, тому перед аналізом ці пропуски треба заповнити середніми значеннями.
2. Через ручне введення тексту в колонках зі статтю та результатами КТ виникло багато помилок і зайвих пробілів, тому такі дані не можна аналізувати без очищення.
3. Рахувати звичайне середнє значення або лінійну кореляцію для текстових категорій не можна, бо комп'ютер не розуміє медичної логіки і видає числа, які не мають жодного фізичного сенсу.

In [21]:
print('ВАШЕ ПИТАННЯ:'); print(В['питання']); print()
ВІДПОВІДЬ = """Різниця між ними полягає в тому, чи існує справжній нуль. У шкалі відношень нуль означає, що чогось взагалі немає, тому такі числа можна спокійно ділити чи множити.
Натомість в інтервальній шкалі нуль обрали просто для зручності відліку.
Серед моїх даних інтервальна шкала — це дата «Виписка», а шкала відношень — результат аналізу «Фібрин2». 
Для аналізу «Фібрин2» математика працює чудово: показник 4.0 дійсно рівно вдвічі більший за 2.0. Але з датою виписки ділити не можна.
Якщо поділити 2022 рік на 2021, ми не отримаємо жодної корисної інформації, бо нульовий рік колись обрали умовно, а не тому, що до того моменту часу взагалі не існувало."""
assert len(ВІДПОВІДЬ.strip()) >= 200, 'Відповідь має бути розгорнутою (від 200 символів)'
print(ВІДПОВІДЬ)

ВАШЕ ПИТАННЯ:
У чому різниця між шкалою інтервалів і шкалою відношень? Знайдіть у файлі по одному прикладу кожної та поясніть, яка операція допустима для другої, але не для першої.

Різниця між ними полягає в тому, чи існує справжній нуль. У шкалі відношень нуль означає, що чогось взагалі немає, тому такі числа можна спокійно ділити чи множити.
Натомість в інтервальній шкалі нуль обрали просто для зручності відліку.
Серед моїх даних інтервальна шкала — це дата «Виписка», а шкала відношень — результат аналізу «Фібрин2».
Для аналізу «Фібрин2» математика працює чудово: показник 4.0 дійсно рівно вдвічі більший за 2.0. Але з датою виписки ділити не можна.
Якщо поділити 2022 рік на 2021, ми не отримаємо жодної корисної інформації, бо нульовий рік колись обрали умовно, а не тому, що до того моменту часу взагалі не існувало.

---
# Етап 8. Декларація про використання інструментів ШІ

Користуватися мовними моделями дозволено. Це нормальна інженерна практика.

**Обов'язковою є прозорість:** ви вказуєте, де саме і як скористалися інструментом —
так само, як у науковій статті вказують використане програмне забезпечення.
Задекларована допомога порушенням не є.

Порушенням є інше: здати роботу, яку ви не можете пояснити. На захисті вас
попросять показати конкретний рядок свого коду, пояснити, чому він саме такий,
і внести в нього невелику зміну на місці.

Для кожного етапу оберіть одне з формулювань:

* `'ні'` — інструментами ШІ не користувався
* `'синтаксис'` — питав про назву функції або синтаксис, код писав сам
* `'код, перевірено'` — код згенеровано, я його прочитав, перевірив і розумію
* `'текст, перероблено'` — згенеровано чернетку тексту, яку я переписав по суті
* `'текст, як є'` — згенерований текст залишено майже без змін

In [22]:
ДЕКЛАРАЦІЯ = {
    'етап 1 — паспорт змінних':        'ні',
    'етап 2 — допустимі статистики':   'синтаксис',
    'етап 3 — безглузді числа':        'ні',
    'етап 4 — міра зв’язку':           'синтаксис',
    'етап 5 — підготовка до моделі':   'код, перевірено',
    'етап 6 — виправлення аналізу':    'текст, перероблено',
    'етап 7 — висновки й відповідь':   'ні',
}

ЩО_САМЕ_Я_ПЕРЕВІРИВ = 'Я перевірив, як методи pandas обробляють різні типи шкал, переконався у правильності вибору міри зв\'язку та протестував очищення даних перед кодуванням.'
ПІДТВЕРДЖУЮ = True     # я можу пояснити кожен рядок свого коду
                        # і внести в нього зміни на вимогу під час захисту

In [23]:
# --- ФІНАЛЬНА САМОПЕРЕВІРКА ---
ФОРМУЛЮВАННЯ = {'ні', 'синтаксис', 'код, перевірено', 'текст, перероблено', 'текст, як є'}

перевірки = {
    'заповнено титульні поля':        bool(ПРІЗВИЩЕ_ІМЯ and ГРУПА and НОМЕР),
    'етап 1: паспорт із 8 стовпців':  all(ПАСПОРТ[c][0] and ПАСПОРТ[c][1] for c in МОЇ),
    'етап 3: три безглузді числа':    len(БЕЗГЛУЗДІ) >= 3,
    'етап 4: міру обрано й пояснено': bool(ОБРАНА_МІРА and len(ЧОМУ_САМЕ_ВОНА) >= 40),
    'етап 5: підготовку описано':     all(len(ПІДГОТОВКА[c].strip()) >= 15 for c in МОЇ),
    'етап 6: знайдено 10 помилок':    len(ВИПРАВЛЕННЯ) == 10,
    'етап 7: три висновки':           len(ВИСНОВКИ) >= 3,
    'етап 7: відповідь на питання':   len(ВІДПОВІДЬ.strip()) >= 200,
    'декларацію заповнено':           all(v in ФОРМУЛЮВАННЯ for v in ДЕКЛАРАЦІЯ.values()),
    'опис перевірки ≥ 120 символів':  len(ЩО_САМЕ_Я_ПЕРЕВІРИВ.strip()) >= 120,
    'підтвердження авторства':        ПІДТВЕРДЖУЮ is True,
}

print('ЧЕК-ЛИСТ ГОТОВНОСТІ')
print('=' * 52)
for назва, ок in перевірки.items():
    print(('  ГОТОВО     ' if ок else '  НЕ ГОТОВО ') + назва)
print('=' * 52)

assert all(перевірки.values()), 'Робота не готова до здачі — див. чек-лист вище'
print()
print(f'Робота варіанта {В["варіант"]} готова до захисту.')
print(f'{ПРІЗВИЩЕ_ІМЯ}, {ГРУПА}')

ЧЕК-ЛИСТ ГОТОВНОСТІ
====================================================
  ГОТОВО     заповнено титульні поля
  ГОТОВО     етап 1: паспорт із 8 стовпців
  ГОТОВО     етап 3: три безглузді числа
  ГОТОВО     етап 4: міру обрано й пояснено
  ГОТОВО     етап 5: підготовку описано
  ГОТОВО     етап 6: знайдено 10 помилок
  ГОТОВО     етап 7: три висновки
  ГОТОВО     етап 7: відповідь на питання
  ГОТОВО     декларацію заповнено
  ГОТОВО     опис перевірки ≥ 120 символів
  ГОТОВО     підтвердження авторства
====================================================

Робота варіанта 4 готова до захисту.
Роман Бойко, ШІ-32

---
### Перед здачею

Виконайте **Kernel → Restart & Run All**. Ноутбук має пройти згори донизу
без жодної помилки — це перше, що перевіряється на захисті.